### ISSUE TITLE
bereal token expiring after a day

### ISSUE THREAD

**Issue by omtoi101** [notmarek/BeFake#94] opened 2023-05-04 06:56 UTC
`File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 28, in wrapper
    raise Exception("No token found, are you logged in?")
Exception: No token found, are you logged in?
`
I run a bot 24/7 on a vps i check back on it and after about a day it starts throwing this exception and i need to re log in with my phone num.
can provide more info if needed

**Comment by SHADOW-13-WALKER** [comment] 2023-05-04 09:07
BeReal introduced a change to the API so now you need to maintain a stable login in connection, add the command "refresh" to your code between now and then, it prevents you from getting logged out, like every 30 min !

**Comment by Smart123s** [comment] 2023-05-04 14:29
Duplicate of #89 

> BeReal introduced a change to the API so now you need to maintain a stable login in connection, the token expires after 2~3 hours, add the command "refresh" to your code between now and then, it prevents you from getting logged out, like every 30 min !

There's no need to run an extra command, the token is refreshed automatically each time BeFake starts up (if the token has expired). The problem relies in the refresh process itself.

**Closed** 2023-05-05 20:00 UTC
