### ISSUE TITLE
Can't share a bereal (upload a picture to the servers)

### ISSUE THREAD

**Issue by SHADOW-13-WALKER** [notmarek/BeFake#82] opened 2023-04-26 01:24 UTC
befake.py post -v friends -r 0 -R false data\photos\primary.webp data\photos\secondary.webp

Traceback (most recent call last):
  File "C:\Users\SCHUMI\Documents\BeFake\befake.py", line 6, in <module>
    cli(obj={})
  File "C:\Users\SCHUMI\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\SCHUMI\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\SCHUMI\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\SCHUMI\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\SCHUMI\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\SCHUMI\Documents\BeFake\BeFake\__main__.py", line 29, in wrapper
    return func(bf, *args, **kwargs)
  File "C:\Users\SCHUMI\Documents\BeFake\BeFake\__main__.py", line 212, in post
    r = Post.create_post(bf, primary=primary_bytes, secondary=secondary_bytes, is_late=False, visibility=visibility, caption=caption, location=loc, retakes=retakes, resize=resize)
  File "C:\Users\SCHUMI\Documents\BeFake\BeFake\models\post.py", line 102, in create_post
    raise Exception(f"Error making the post: {res.status_code}")
Exception: Error making the post: 403

Any help please !?

**Comment by sanderDijkxhoorn** [comment] 2023-04-26 09:22
Take a look at #79

**Comment by VxlerieUwU** [comment] 2023-04-26 10:08
Duplicate of #79

**Comment by SHADOW-13-WALKER** [comment] 2023-04-26 10:25
still can't upload anything even when using #79 !!!

**Comment by sanderDijkxhoorn** [comment] 2023-04-26 10:51
> still can't upload anything even when using #79 !!!

Have you used the vonage backend?

**Comment by sanderDijkxhoorn** [comment] 2023-04-26 13:27
> > > still can't upload anything even when using #79 !!!
> > 
> > 
> > Have you used the vonage backend?
> 
> yes I did, it fixes the login issue and retrieving posts from the feed, but not the uploading

Ah I have not looked into that, instant realmoji’s worked fine for me tho.

**Comment by VxlerieUwU** [comment] 2023-04-26 13:57
I'll look into it

**Comment by Stanley1551** [comment] 2023-05-07 09:46
> I'll look into it

Is there any progress made so far? I have the same issue uploading posts.

**Comment by SHADOW-13-WALKER** [comment] 2023-05-07 14:11
> > I'll look into it
> 
> Is there any progress made so far? I have the same issue uploading posts.

Nope, couldn't fixe it

**Comment by tandpfun** [comment] 2023-05-09 00:58
Doesn't work for me either ^^

**Closed** 2023-06-01 18:01 UTC
Labels: bug
